import { StyleSheet } from 'react-native';
import { scale, vw, vh } from '../utils/scaling';

const styles = StyleSheet.create({
    normalText: {
        fontSize: scale(16),
    },
    smallText: {
        fontSize: scale(14),
    },
    smallerText: {
        fontSize: scale(12),
    },
    boldText: {
        fontWeight: "bold",
    },
    whiteText: {
        color: '#fafefd',
    },
    menuText: {
        fontSize: scale(16),
        color: 'white',
        position: 'absolute',
        fontWeight: "bold",
    },
    splashScreenImage: {
        flex: 1,
        width: 60 * vw,
        height: 15 * vh,
        resizeMode: 'contain',
        marginTop: 2 * vh,
        marginBottom: 2 * vh,
    },
    splashScreen: {
        backgroundColor: '#323C6D',
        height: 100 * vh,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    splashTextInput: {
        marginBottom: 1 * vh,
        marginTop: 1 * vh,
        height: 7 * vh,
        width: 80 * vw,
        backgroundColor: 'white',
        fontSize: scale(15),
        paddingLeft: 2 * vw,
    },
    splashButton: {
        height: 7 * vh,
        width: 80 * vw,
        justifyContent: 'center',
        alignItems: 'center',
    },
    smallButton: {
        height: 7 * vh,
        width: 30 * vw,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loginBtn: {
        marginBottom: 0,
        marginTop: 1 * vh,
        backgroundColor: '#42BCF0',
    },
    forgotBtn: {
        marginTop: 1 * vh,
        marginBottom: 12 * vh,
    },
    signupBtn: {
        marginTop: 3 * vh,
        marginBottom: 2 * vh,
    },
    shortBtn: {
        height: 7 * vh,
        width: 40 * vw,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#42BCF0',
    },
    checkbox: {
        width: 6 * vw,
        height: 6 * vh,
        resizeMode: 'contain',
        marginTop: 2 * vh,
        marginBottom: 2 * vh,
    },
    row: {
        flexDirection: 'row',
    },
    profText: {
        marginTop: 1 * vh,
        marginBottom: -4 * vh,
        marginLeft: 12 * vw,
    },
    checkboxContainer: {
        marginLeft: 5 * vw,
        marginBottom: -2 * vh,
        marginTop: -2 * vh,
    },
    homeScreen: {
        height: 93 * vh,
        display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'center',
        backgroundColor: '#323C6D',
    },
    homeScreenLoading: {
        height: 93 * vh,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#323C6D',
    },
    homeHeaderScreen: {
        height: 7 * vh,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#323C6D',
    },
    homeImage: {
        width: 9 * vw,
        height: 9 * vh,
        resizeMode: 'contain',
        tintColor: '#6B7299',
    },
    backImage: {
        width: 12 * vw,
        height: 12 * vh,
        padding: 1 * vh,
        resizeMode: 'contain',
        tintColor: '#6B7299',
    },
    hamburgerImage: {
        width: 9 * vw,
        height: 9 * vh,
        resizeMode: 'contain',
        tintColor: '#6B7299',
    },
    hr: {
        marginBottom: 2 * vh,
        marginTop: 2 * vh,
    },
    hrl: {
        borderBottomColor: '#323C6D',
        borderBottomWidth: 1,
        marginBottom: 2 * vh,
        marginTop: 2 * vh,
    },
    circle: {
        marginLeft: 5 * vw,
        marginRight: 5 * vw,
        width: 10,
        height: 10,
        borderRadius: 5,
    },
    content: {
        width: 96 * vw,
        marginTop: 3 * vh,
        marginBottom: 3 * vh,
        marginLeft: 2 * vw,
        marginRight: 2 * vw,
        backgroundColor: 'white',
        borderRadius: 10,
    },
    contentTitle: {
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        alignItems: 'center',
        backgroundColor: '#F6F6F6',
        borderBottomColor: '#757575',
        borderBottomWidth: StyleSheet.hairlineWidth,
        paddingTop: 1 * vh,
        paddingBottom: 1 * vh,
    },
    fullWidth: {
        width: 96 * vw,
    },
    contentItem: {
        flexDirection: "row",
        alignItems: "center",
        borderBottomColor: '#757575',
        borderBottomWidth: StyleSheet.hairlineWidth,
        paddingTop: 1 * vh,
        paddingBottom: 1 * vh,
        paddingLeft: 3 * vw,
        paddingRight: 3 * vw,
    },
    contentItemNoBorder: {
        flexDirection: "row", 
        alignItems: "center",
        paddingTop: 1 * vh,
        paddingBottom: 1 * vh,
        paddingLeft: 3 * vw,
        paddingRight: 3 * vw,
    },
    homeText: {
        fontSize: scale(14),
        color: 'grey',
        marginLeft: 35 * vw,
    },
    rooterHomeText: {
        fontSize: scale(14),
        color: 'grey',
        marginLeft: 29 * vw,
    },
    wifiText: {
        fontSize: scale(14),
        color: 'grey',
        marginLeft: 20 * vw,
    },
    deviceText: {
        fontSize: scale(14),
        color: 'grey',
    },
    modalFrame: {
        width: 100 * vw,
        height: 100 * vh,
        display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'center',
        backgroundColor: '#323C6D',
    },
    menu: {
        marginTop: 7 * vh,
        height: 93 * vh,
        position: 'absolute',
        right: 0,
        backgroundColor: '#323C6D',
        zIndex: 2,
        alignItems: 'center',
        justifyContent: 'center',
    },
    menuItem: {
        paddingLeft: 3 * vw,
        paddingRight: 3 * vw,
        flexDirection: 'row',
    },
    iconBuffer: {
        paddingLeft: 4 * vw,
        flex: 1,
    },
    registrationField: {
        height: 7 * vh,
        width: 80 * vw,
        backgroundColor: 'white',
        fontSize: scale(15),
        paddingLeft: 2 * vw,
        marginBottom: 2 * vh,
        marginHorizontal: 10 * vw,
    },
});

export default styles;